### ISSUE TITLE
Missing items and recipes

### ISSUE THREAD

**Issue by jaidaken** [Donne431/Ice_and_Fire_Delight-1.20.1#1]
> 12.06 19:29:32 [Server] main/[ERROR] [minecraft/RecipeManager]: Parsing error loading recipe ice_and_fire_delight:lightning_sausage_campfire_cooking: com.google.gson.JsonSyntaxException: Unknown item 'ice_and_fire_delight:raw_lightning_sausage'
> 12.06 19:29:32 [Server] main/[ERROR] [minecraft/RecipeManager]: Parsing error loading recipe ice_and_fire_delight:raw_lightning_sausage: com.google.gson.JsonSyntaxException: Unknown item 'ice_and_fire_delight:lightning_minced_meat'
> 12.06 19:29:32 [Server] main/[ERROR] [minecraft/RecipeManager]: Parsing error loading recipe ice_and_fire_delight:lightning_sausage_smoking: com.google.gson.JsonSyntaxException: Unknown item 'ice_and_fire_delight:raw_lightning_sausage'

it seems like a few of your items are missing!

**Comment by Donne431** [comment]
Sorry, **it's my mistake**, I left recipes for items that aren't in the mod yet. In the next update - **0.1.5**, I will try to fix this bug.

**Comment by Donne431** [comment]
0.1.5 is out and I have added the missing items. Please check if you still have this bug, I just don't have this error on my test server anymore.

**Comment by jaidaken** [comment]
Those errors do seem to be gone, but I did get this, not sure if it's on my end though!

`21.06 18:17:49 [Server] main/[WARN] [ne.mi.re.ForgeRegistry/REGISTRIES]: Registry minecraft:item: Object did not get ID it asked for. Name: ice_and_fire_delight:lightning_minced_meat Expected: 6851 Got: 6289
21.06 18:17:49 [Server] main/[WARN] [ne.mi.re.ForgeRegistry/REGISTRIES]: Registry minecraft:item: Object did not get ID it asked for. Name: ice_and_fire_delight:raw_lightning_sausage Expected: 6852 Got: 6290
21.06 18:17:49 [Server] main/[WARN] [ne.mi.re.ForgeRegistry/REGISTRIES]: Registry minecraft:item: Object did not get ID it asked for. Name: ice_and_fire_delight:lightning_sausage Expected: 6853 Got: 6291
21.06 18:17:49 [Server] main/[WARN] [ne.mi.re.ForgeRegistry/REGISTRIES]: Registry minecraft:item: Object did not get ID it asked for. Name: ice_and_fire_delight:mini_pizza Expected: 6862 Got: 6292
21.06 18:17:49 [Server] main/[WARN] [ne.mi.re.ForgeRegistry/REGISTRIES]: Registry minecraft:item: Object did not get ID it asked for. Name: ice_and_fire_delight:mini_pizza_blank Expected: 6863 Got: 6293
21.06 18:17:49 [Server] main/[WARN] [ne.mi.re.ForgeRegistry/REGISTRIES]: Registry minecraft:item: Object did not get ID it asked for. Name: ice_and_fire_delight:raw_mini_pizza_blank Expected: 6864 Got: 6294`

**Comment by Donne431** [comment]
Yeah, but this error is solved quite simply, all you need is to restart the server, this error appears only at the first start of the server, and after it does not appear.

**Comment by jaidaken** [comment]
Amazing, good work!
