### ISSUE TITLE
Rendering Crash with malum-1.20.1-1.6.5/lodestone-1.20.1-1.6.4

### ISSUE THREAD

**Issue by border999** [Donne431/Ice_and_Fire_Delight-1.20.1#3]
https://gist.github.com/border999/151d141bf80d723dee43a8a1b355add8

**Comment by Donne431** [comment]
Can I get more information? At what situation do you have the game crashes? Are there any crashes without IaFD or malum?

**Comment by border999** [comment]
It was a crash on game startup if memory serves. Odd that it isn't happening now. Some kind of intermitent issue from Malum perhaps. Will investigate, closing issue for now.
